name: spotify_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - dagshub
      - scikit-learn==1.5.2
      - pandas
      - numpy
